// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyqeqzmtmoijwrnqljxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5cWVxem10bW9pandybnFsanh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDI3MDgsImV4cCI6MjA2NjI3ODcwOH0.mtC0BE8f-zOldwqCbuv4ZssyHPSvZ0uef9SRnKRARWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);